import {
	YisButton,
	YisButtonGroup,
	YisIcon,
	YisCollapse,
	YisCollapseItem,
	YisAlert,
	YisTooltip,
	YisPopconfirm,
	YisDropdown,
	YisDropdownItem,
	YisMessage,
	YisMessageBox,
	YisNotification,
	YisInput,
	YisLoading,
	YisLoadingService,
	YisSwitch,
	YisSelect,
	YisOption,
	YisForm,
	YisFormItem,
} from '@salmon-element/components';
import type { Plugin } from 'vue';

export default [
	YisButton,
	YisButtonGroup,
	YisIcon,
	YisCollapse,
	YisCollapseItem,
	YisAlert,
	YisTooltip,
	YisPopconfirm,
	YisDropdown,
	YisDropdownItem,
	YisMessage,
	YisMessageBox,
	YisNotification,
	YisInput,
	YisLoading,
	YisLoadingService,
	YisSwitch,
	YisSelect,
	YisOption,
	YisForm,
	YisFormItem,
] as Plugin[];
